# Generated by Django 5.2.7 on 2025-11-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('total_live_class_count', models.CharField(blank=True, max_length=2, null=True)),
                ('total_assignment_count', models.CharField(blank=True, max_length=2, null=True)),
                ('total_test_count', models.CharField(blank=True, max_length=2, null=True)),
                ('start_day', models.DateTimeField(blank=True, null=True)),
                ('end_day', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
        ),
    ]
