# Generated by Django 5.2.7 on 2025-11-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='total_assignment',
            new_name='total_assignment_count',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='total_live_class',
            new_name='total_live_class_count',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='total_test',
            new_name='total_test_count',
        ),
    ]
