# Generated by Django 5.2.7 on 2025-11-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_created_at_module_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='updated_at',
        ),
    ]
