# Generated by Django 5.2.7 on 2025-11-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
